# Form implementation generated from reading ui file 'c:\Users\jay\Desktop\生醫資料探勘HW\HW1_Version\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Load = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Load.sizePolicy().hasHeightForWidth())
        self.Load.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Load.setFont(font)
        self.Load.setStyleSheet(" QPushButton {\n"
"                border: 1px solid #199909;\n"
"                border-radius: 15px;\n"
"                color: white;\n"
"                font: bold;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 0.86,stop: 0 #24B375, stop: 1 #7CB31B);\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #6A4005;\n"
"                border: 7px dashed #09940E;\n"
"                border-radius: 15px;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                color: white;\n"
"                font: bold;\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 0.86,stop: 0 #24B375, stop: 1 #7CB31B);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 1px solid #333333;\n"
"                background-color: #127005;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                color: white;\n"
"                font: bold;\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 0.67, stop: 0 #127005, stop: 1 #127005);\n"
"            }\n"
"             QPushButton:checked {\n"
"                border: 1px solid #333333;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                color: white;\n"
"                font: bold;\n"
"            }\n"
"")
        self.Load.setObjectName("Load")
        self.horizontalLayout_3.addWidget(self.Load)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Search = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search.sizePolicy().hasHeightForWidth())
        self.Search.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Search.setFont(font)
        self.Search.setStyleSheet(" QPushButton {\n"
"                border: 1px solid #199909;\n"
"                border-radius: 15px;\n"
"                color: white;\n"
"                font: bold;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 0.86,stop: 0 #24B375, stop: 1 #7CB31B);\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #6A4005;\n"
"                border: 7px dashed #09940E;\n"
"                border-radius: 15px;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                color: white;\n"
"                font: bold;\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 0.86,stop: 0 #24B375, stop: 1 #7CB31B);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 1px solid #333333;\n"
"                background-color: #127005;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                color: white;\n"
"                font: bold;\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 0.67, stop: 0 #127005, stop: 1 #127005);\n"
"            }\n"
"             QPushButton:checked {\n"
"                border: 1px solid #333333;\n"
"                padding-left:10px;\n"
"                padding-right:10px;\n"
"                color: white;\n"
"                font: bold;\n"
"            }\n"
"")
        self.Search.setObjectName("Search")
        self.horizontalLayout_2.addWidget(self.Search)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setText("")
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_5.addWidget(self.title)
        self.Content_analyze = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Content_analyze.setFont(font)
        self.Content_analyze.setText("")
        self.Content_analyze.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Content_analyze.setObjectName("Content_analyze")
        self.verticalLayout_5.addWidget(self.Content_analyze)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.Search_result = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Search_result.setFont(font)
        self.Search_result.setText("")
        self.Search_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Search_result.setObjectName("Search_result")
        self.verticalLayout_6.addWidget(self.Search_result)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 5)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_4.setStretch(0, 9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Load.setText(_translate("MainWindow", "載入資料"))
        self.label_4.setText(_translate("MainWindow", "已上傳檔案"))
        self.Search.setText(_translate("MainWindow", "搜尋/統計"))
        self.label_2.setText(_translate("MainWindow", "搜尋結果"))
